# Generated by Django 4.1.7 on 2023-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_bookappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngravingBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Engraved_text', models.CharField(max_length=500)),
                ('font_name', models.CharField(max_length=100)),
                ('font_size', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
